language: java
install: true
jdk:
  - oraclejdk8
script:
  - ./gradlew build
after_success:
  - ./gradlew jacocoTestReport coveralls
env:
  - COVERALLS_REPO_TOKEN=MagicDtoBuilder
  - CI_NAME=travis-ci